server:
  port: 9001
spring:
  application:
    name: user-service
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.107:8837, 192.168.0.107:8848, 192.168.0.107:8859
      config:
        server-addr: 192.168.0.107:8837, 192.168.0.107:8848, 192.168.0.107:8859
        file-extension: yaml
    gateway:
      discovery:
        locator:
          enabled: true
  redis:
    host: localhost
    port: 6319
    timeout: 10s
    lettuce:
      pool:
        max-active: 50
        max-idle: 50
        max-wait: -1ms
        min-idle: 0
