server:
  port: 8500
spring:
  application:
    name: oauth2-service
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.107:8837, 192.168.0.107:8848, 192.168.0.107:8859
      config:
        server-addr: 192.168.0.107:8837, 192.168.0.107:8848, 192.168.0.107:8859
        file-extension: yaml

    gateway:
      discovery:
        locator:
          enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=UTC&useSSL=false
    username: root
    password: root
